### ISSUE TITLE
Improve example

### ISSUE THREAD

**Issue by grabbou** [react-native-community/react-native-side-menu#161]
Make it more similar to `UIExplorer` demo in React Native, so that:
1. It renders List of available demos on home page
2. On select, it renders particular example.

What to show-case:
- Navigator example
- Custom animation (e.g. my fancy scale down animation)

What do you guys think about that?

**Comment by flyingace** [comment]
I definitely think you should include an example with Navigator. In the code snippet you show `const menu = <Menu navigator={navigator}/>` but where does the `{navigator}` come from?

**Comment by grabbou** [comment]
@Kureev can we rewrite examples to be just `one example` with ListView (that links to sub-examples), just like UIExplorer? So that we have `Basic menu`, `Menu with Navigator`, `Menu with Active item` etc. ?

**Comment by Kureev** [comment]
We can, if you have time to do it :+1:

**Comment by billybil** [comment]
@flyingace yes, I was just looking how to integrate the navigator into the menu... did you ever figure out how to do this? The snippet has the navigator but the example is just a scrollview. 

Sidemenus main functionality would be navigation so an example in this area would be much appreciated :)

**Comment by g3r4n** [comment]
made a navigator example in PR #206
