### ISSUE TITLE
menu gets stuck sometimes

### ISSUE THREAD

**Issue by morenoh149** [react-native-community/react-native-side-menu#169]
Testing on a real android device. While doing some user research my users commonly get the side menu stuck. Using gestures sometimes the logic for completely opening or closing the menu is insufficient (or doesn't cover some edge case) and the side menu stays ~10% (of the side menu's width) open.

Has anyone else encountered this? Does this ever happen on ios?

Here's a screenshot
![contactsprosidemenubug](https://cloud.githubusercontent.com/assets/587438/12072244/2b086a36-b0a3-11e5-9cab-f2b42aa92ddf.png)

**Comment by DocLoLiday** [comment]
I fixed this issue by setting negotiatePan={true}. It seems like if you gesture up or down even a little bit, it will stop the horizontal gesture and lock the drawer position at that point. negotiatePan attempts to only resolve horizontal gestures, and fixes this issue. If you want smoother transition, you can set acceptPan={false} and the drawer will open and close at its set speed. Or set it to true if you want fine control of the drawer, whichever you feel is a better experience.

**Comment by morenoh149** [comment]
@DocLoLiday does that mean we need documentation for these behaviors?

**Comment by artem-russkikh** [comment]
Same problem.

`negotiatePan` is a prop of https://github.com/root-two/react-native-drawer package

I think that is possible to implement something similar to `negotiatePan` in react-native-side-menu

**Comment by sodik82** [comment]
It happens to me also (real android device). More frequently in debug but happens also in release build.

**Comment by sodik82** [comment]
@DocLoLiday can you share more details about your fix - e.g. where did you set `negotiatePan={false}` etc. Thanks

**Comment by morenoh149** [comment]
@sodik82 I'm pretty sure @DocLoLiday did not mean `react-native-side-menu` he meant `react-native-drawer`

**Comment by seb0zz** [comment]
Did anyone of you guys find a solution for this issue?

**Comment by jorgeluis11** [comment]
+1 same issue

**Comment by sneerin** [comment]
+1 having same issue

**Comment by sneerin** [comment]
+1

**Comment by pcxiong** [comment]
same problem, any fix for this issue ?

**Comment by seb0zz** [comment]
I think the best solution is to use the native [DrawerLayoutAndroid](https://facebook.github.io/react-native/docs/drawerlayoutandroid.html)

**Comment by jaseemabbas** [comment]
+1 same issue.

**Comment by cgarnier** [comment]
+1 with a scroll view inside

**Comment by pqkluan** [comment]
I found a way to band-aid this issue. The idea is to check if the drawer is stuck in a particular range (10 to 50 dpi) then de-stuck it. To do that, we need to compare the latest left offset, and the counter of the side menu open/close times.

Add this to the component that renders the SideMenu
```
    constructor(props) {
        this.state = {
            isDrawerOpen: false,
        };
        this.deStuck = () => this.setState({isDrawerOpen: true}, () => this.setState({isDrawerOpen: false}));
        this.switchCount = 0;
        this.lastLeftOffset = 0;
        this._onChange = () => this.switchCount += 1; //Update open/close counter
        this._onMove = (leftOffset) => {
            this.lastLeftOffset = leftOffset;
            if (leftOffset > 10 && leftOffset <= 50) {  //The side menu usually stuck at this range, the smaller the check range, the better the performace
                const tempSwitchCount = this.switchCount; //save the current count of open/close times
                const tempLeftOffset = this.lastLeftOffset; //save the current left offset
                Timer.setTimeout(() =>
                    this.switchCount === tempSwitchCount && // if open/close event haven't trigger
                    this.lastLeftOffset === tempLeftOffset && // and the current offset is still the same
                    this.deStuck() // then unstuck
                    , 1000
                );
            }
        };
    }
```
and the Sidemenu
```
<SideMenu
    isOpen={this.state.isDrawerOpen}
    onChange={this._onChange}
    onMove={this._onMove}
    menu={<Drawer goToScreen={this.goToScreen}/>}
    ...
    >
        <App/>
</SideMenu>
```

Hope this help.
