### ISSUE TITLE
Add callback to know when user starts dragging and stops dragging

### ISSUE THREAD

**Issue by adrienbrault** [react-native-community/react-native-side-menu#188]
Hi,

I would like to be able to hide the status bar when the user is dragging, kind of like in the slack ios app.

**Comment by Kureev** [comment]
Is it `animationFunction` what you were looking for?

**Comment by grabbou** [comment]
No, I don't think that's the correct place to hook that up. Just make menu props driven, keep `isOpen` property in state (and sync it with menu). In componentDidUpdate, react to state.isMenuOpened changes by calling StatusBarIOS.setHidden etc.

**Comment by adrienbrault** [comment]
@Kureev No, I want to know when the user is panning, not when the open/close animation starts/ends.

@grabbou That's pretty much what I have right now. However I would like the status bar to be hidden as soon as the user starts panning (right now when the user starts panning the status bar is still visible, and when the user stops panning, it then hides).

**Comment by Kureev** [comment]
I believe you can use `onSliding` (new API in `1.1.0`) for that purpose now. I'm about to close this one due two reasons:
1. It is inactive for more than a year
2. You can now use `onSliding` in order to achieve your goal
