### ISSUE TITLE
integration react-native-swiper always back to first page

### ISSUE THREAD

**Issue by L-Jovi** [react-native-community/react-native-side-menu#201]
sorry to trouble, I try to use another smart component [react-native-swiper](https://github.com/leecade/react-native-swiper) with existed **react-native-side-menu** application, but I found 2 issue.
1. I can't opening side menu, in other words, it's hard to recognize my gesture of dragging.
2. even if when I opening side-menu the swiper always back to first page at same time :(

how should I fix? maybe some suggestion could help me.

thanks for your time,

regards.

**Comment by Kureev** [comment]
Hi @L-Jovi,

To help you with your issue I need to figure out how you see this interaction? I mean how you want to distinguish the gesture for side-menu and a gesture for swiper?

**Comment by L-Jovi** [comment]
Maybe I don't express clearly, provide below image.

![demo](https://cloud.githubusercontent.com/assets/7262199/13553128/21787648-e3b9-11e5-9cca-df10c43d1964.gif)

as my first issue, I want to drag side menu from screen edge and at the same time I hope that swiper don't move, but now I just drag it inside navigation :(

the second issue, I mean that even if when I drag side menu inside navigation, the swiper seem back to first index of page, I don't think it's bug of both swiper and side-menu component, but I have no idea to solve it..

![demo](https://cloud.githubusercontent.com/assets/7262199/13553161/71d190b0-e3ba-11e5-8220-ab560131b547.gif)

**Comment by Kureev** [comment]
> I want to drag side menu from screen edge and at the same time I hope that swiper don't move, but now I just drag it inside navigation :(

Make width of the slider a bit less to add a space for `side-menu` or ask the same question at the swiper component, because there is no way how `side-menu` can prevent other components to process swipe gesture.

**Comment by Kureev** [comment]
> I mean that even if when I drag side menu inside navigation, the swiper seem back to first index of page, I don't think it's bug of both swiper and side-menu component, but I have no idea to solve it..

You should set an `index` to `<Swiper />` component you use. Then, after re-render, you'll be still on the same page as you were before.

**Comment by L-Jovi** [comment]
@Kureev  thanks for your suggestion, I'll try it :)
