### ISSUE TITLE
could I set right style when I specify menuPosition={'right'}

### ISSUE THREAD

**Issue by L-Jovi** [react-native-community/react-native-side-menu#202]
I specify `menuPosition={'right'}` of sideMenu, and all children element disappeared.

then I notice that side menu bespread whole screen while I can't see them in my viewport, so I set styles below.

```
container: {
  flex: 1,
  left: window.width * 1 / 3,
  width: window.width * 2 / 3,
}
```

now I could layout correctly, but my question is, why shouldn't I set right of styles, like below

```
// not work
container: {
  flex: 1,
  right: 0,
  width: window.width * 2 / 3,
}
```

thanks for your time :)

**Comment by Kureev** [comment]
I think `right: 0` would also works, but the width is still to big to see your elements. Try to use `textAlign: 'right'` or `alignItems: 'flex-end'`.

**Comment by L-Jovi** [comment]
@Kureev  thanks for your reply, I try your idea but also not work, maybe some other reason cause `right: 0` work incorrectly.

in any case, `left: window.width * 1 / 3` seem normally, thanks for your smart __react-native-side-menu__ :)

**Comment by Kureev** [comment]
There is still a room for improvements, but I don't have enough time to work on it :(

**Comment by Kureev** [comment]
Can you explain me how to reproduce a bug?

**Comment by L-Jovi** [comment]
I'm not sure you could reappear the same bug as mine, but I'll try my best to select relevant code below.

a little messy :)


__App.js__

    <SideMenu
            menu={<Menu />}
            isOpen={this.state.isOpen}
            onChange={(isOpen) => this.updateMenuState(isOpen)}
            menuPosition={'right'}  // I change default position here
            disableGestures={true}>  // here I disable geatures
      <CustomNavigator style={{ flex: 1, position: 'absolute', height: 64, top: 0, left: 0, }} />
      <CustomView style={{ flex: 1, marginTop: 64, }}>
      <Swiper style={{ flex: 1, }}>  // from leecade/react-native-swiper/
        <ScrollView style={{ flex: 1, }}> // some custom component </ScrollView>
      </Swiper>
      </CustomView>
    </SideMenu>


__Menu.js__

    const window = Dimensions.get('window');

    <View style={{ flex: 1, }}>
      <View style={styles.container}>
      </View>
    </View>

    container: {
        flex: 1,
        position: 'absolute',
        left: window.width * 1 / 3,  // right: 0  can't work :(
        top: 0,
        width: window.width * 2 / 3,
        height: window.height,
  },

although above code work normally now, but I also want to find out why `right: 0` not  layout incorrectly.

regards.

thanks for your patience :)

**Comment by Kureev** [comment]
Thanks for your example! I'll do my best to figure out why it doesn't work for you :+1:

**Comment by eljago** [comment]
a quick fix for this could be to go to index.js and edit the SideMenu's render function like this:

    render() {
        if (this.props.menuPosition == 'right') {
            var offsetStyle = {left: deviceScreen.width - this.props.openMenuOffset};
        }
        else {
            var offsetStyle = {right: deviceScreen.width - this.props.openMenuOffset};
        }
        const menu = <View style={[styles.menu, offsetStyle]}>{this.props.menu}</View>;

        return (
            <View style={styles.container} onLayout={this.onLayoutChange.bind(this)}>
                {menu}
                {this.getContentView()}
            </View>
        );
    }

**Comment by Kureev** [comment]
I think this one can be closed.
