### ISSUE TITLE
Breaking change in 0.18.1, render order is broken

### ISSUE THREAD

**Issue by charpeni** [react-native-community/react-native-side-menu#217]
It seems since release 0.18.1 the render order is broken.

I have a map with some overlay buttons that trigger the side menu on the right. Under that map I have an ad component and with that setup the side menu slide on top of the ad component.

_Note that I just cleaned my code to remove unwanted components in this exemple._

``` jsx
<View style={styles.container}>
  <SideMenu
    menu={menu}
    isOpen={this.state.isOpen}
    menuPosition={'right'}
  >
    <MapView
      style={styles.map}
      mapType={'hybrid'}
      showsUserLocation
    />
  </SideMenu>
  <Ad />
</View>
```
##### 0.18.0 (Expected behaviour)

<img src="https://cloud.githubusercontent.com/assets/7189823/15059206/f57257b6-12ee-11e6-8afd-ee54622a8115.jpg" height="350">
##### 0.18.1 (Actual behaviour)

<img src="https://cloud.githubusercontent.com/assets/7189823/15059208/faf8c8d2-12ee-11e6-99a6-c1bafdc2dbd5.jpg" height="350">

Could be related to #198 #214.

**Comment by Kureev** [comment]
Hard to say what triggered this issue without taking a look on styles. But correct me if I'm wrong: adding `position: 'absolute', bottom: 0` is gonna fix the problem, right?

**Comment by charpeni** [comment]
```javascript
const styles = StyleSheet.create({
  container: {
    flex: 1,
    marginTop: 40,
  },
  sidemenu: {
    flex: 1,
  },
});

export default class SideMenuOrderIssue extends React.Component {
  render() {
    const menu = <View />;

    return (
      <View style={styles.container}>
        <Text> Before side menu </Text>
        <SideMenu
          style={styles.sidemenu}
          menu={menu}
        >
          <Text> 1 </Text>
          <Text> 2 </Text>
          <Text> 3 </Text>
        </SideMenu>
        <Text> After side menu </Text>
      </View>
    );
  }
}
```

##### 0.18.1 & 0.19.0
<img src="https://cloud.githubusercontent.com/assets/7189823/15520872/5d21ad62-21d6-11e6-936a-97ac13438f93.png" height=350 />

##### 0.18.0
<img src="https://cloud.githubusercontent.com/assets/7189823/15520884/72d3aa8e-21d6-11e6-8d7d-921488b99d32.png" height=350 />

**Comment by charpeni** [comment]
@Kureev IMO, it seems that's a big breaking change introduced into `v0.18.1`.

**Comment by Kureev** [comment]
Hey all, it looks pretty outdated and non-actionable. Hope nobody minds if I close this one.
