### ISSUE TITLE
Side menu appear when we navigate back.

### ISSUE THREAD

**Issue by akshaysinghi** [react-native-community/react-native-side-menu#222]
Side menu appear when we navigate back previous route even **isOpen** is false. I get the small glimpse of it.
My menu background color is black (Even also tried making it white).

Any solution developers ;)

**Comment by dozoisch** [comment]
Seems to be related to https://github.com/react-native-fellowship/react-native-side-menu/issues/172

**Comment by Kureev** [comment]
See #172
