### ISSUE TITLE
The sidemenu is not hidden when closed

### ISSUE THREAD

**Issue by stanleycyang** [react-native-community/react-native-side-menu#227]
Using the same styles as the example, this is what I am seeing when the menu is closed / opened:

![screen shot 2016-06-17 at 11 53 51 pm](https://cloud.githubusercontent.com/assets/3037893/16169513/d566eea4-34e6-11e6-8bb8-9b8efad7ef1c.png)

This is the styling I'm using:

```
export const sidebar = StyleSheet.create({
  menu: {
    flex: 1,
    width: window.width,
    height: window.height,
    backgroundColor: 'gray',
    padding: 20,
  },
  avatarContainer: {
    marginBottom: 20,
    marginTop: 20,
  },
  avatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    flex: 1,
  },
  name: {
    position: 'absolute',
    left: 70,
    top: 20,
  },
  item: {
    fontSize: 14,
    fontWeight: '300',
    paddingTop: 5,
  }
});
```

I'm rendering the **SideMenu** at the top:

``` js
render() {
    const { isOpen } = this.state;
    return (
      <SideMenu
        menu={ <Menu /> }
        onChange={(isOpen) => this.updateMenuState(isOpen)}
        isOpen={ isOpen }>

        <View style={ pageStyles.body }>
          <Header toggle={ this.toggleMenu } />
          <NavTabs />
        </View>

      </SideMenu>
    )
  }
```

Not sure why the sidemenu does not hide. Any help would be appreciated.

**Comment by Kureev** [comment]
Hi @stanleycyang!

Sorry for the late response. It's hard to say what goes wrong here without seeing `updateMenuState` and `toggleMenu` functions. I think you can add `console.log(isOpen);` after destructuring operator in the render to see if it pass an expected value.

**Comment by MacKentoch** [comment]
Hi,

Not sure it is a SideMenu bug.

I encounter this issue when SideMenu content is a Navigator and when this navigator's scenes transition is for example `Navigator.SceneConfigs.FloatFromRight`. 

> The problem is that the navigation transition is processing some kind interpolation between x position and the current scene's opacity = it shows SideMenu (which is behind current scene).

My fix was simple and just consisted in replacing transition:
- FROM: 
  - `Navigator.SceneConfigs.FloatFromRight`
- TO EQUIVALENT (without opacity interpolation):
  - `Navigator.SceneConfigs.HorizontalSwipeJump;`

**Comment by kerrison24** [comment]
I'm having the same issue. 

@MacKentoch, I've tried your solution but I'm still experiencing the same issue. Is this more of a styling issue rather than a bug? Either way, I can't seem to solve the issue.

My render function:
`render() {
    const menu = <UserSidebarMenu/>
    return (
      <View style={{height: 500}}>
        <SideMenu
          menu={menu}
          isOpen={this.state.open}
          menuPosition="right">
          <Header
            loaded={this.state.loaded}
            initialMenuState={this.state.open}
            callbackParent={this.childMenuStateChanged.bind(this)}/>
          <View>
            <Text>Main Area</Text>
          </View>
        </SideMenu>
      </View>
    )
  }`

Styling for the menu within the side-menu
`menu: {
    flex: 1,
    width: window.width,
    height: window.height,
    backgroundColor: 'gray',
    padding: 20
  }`

**Comment by kerrison24** [comment]
I'm having the same issue.

@MacKentoch, I've tried your solution but I'm still experiencing the same issue. Is this more of a styling issue rather than a bug? Either way, I can't seem to solve the issue.

My render function:
```javascript
render() {
    const menu = <UserSidebarMenu/>
    return (
      <View style={{height: 500}}>
        <SideMenu
          menu={menu}
          isOpen={this.state.open}
          menuPosition="right">
          <Header
            loaded={this.state.loaded}
            initialMenuState={this.state.open}
            callbackParent={this.childMenuStateChanged.bind(this)}/>
          <View>
            <Text>Main Area</Text>
          </View>
        </SideMenu>
      </View>
    )
}
```
Styling for the menu within the side-menu:
```css
menu: {
    flex: 1,
    width: window.width,
    height: window.height,
    backgroundColor: 'gray',
    padding: 20
}
```

**Comment by MacKentoch** [comment]
@kerrison24 Interesting. In any case, it is a style issue.

But I don't understand where is your Navigator component?
As an example (*maybe it helps*) my **SideMenu + Navigator** always looks something like:
```javascript
      <SideMenu
        menu={
          <View style={{flex:1}}>
            <SideMenuContent
              sideMenuOpened={sideMenuOpened}
              navigate={this.navigate}
            />
          </View>
        }
        isOpen={sideMenuOpened}
        disableGestures={true}
        onChange={this.updateSideMenuState}
        bounceBackOnOverdraw={false}
        openMenuOffset={SCREEN_WIDTH * 0.8}
        >
        <Navigator
          ref="navigator"
          initialRoute={ DEFAULT_ROUTE }
          sceneStyle={ styles.navigator }
          renderScene={this.renderScene}
          configureScene={this.configureScene}
          navigationBar={
            <Navigator.NavigationBar
              routeMapper={this.renderRouteMapper()}
              style={styles.navBar}
            />
          }
        />
      </SideMenu>

  // configure scene transition animation:
  configureScene = (route) => {
    switch (route.id) {
      case 'SOME_ROUTE_ID':
        return Navigator.SceneConfigs.PushFromRight;
      default:
        return Navigator.SceneConfigs.FadeAndroid;
    }
  }
```

In your style: do you really need to limit height to 500:
```javascript
<View style={{height: 500}}>
```

when sidemenu is full screen:
```javascript
menu: {
    flex: 1,
    width: window.width,
    height: window.height,
    backgroundColor: 'gray',
    padding: 20
}
```

It is difficult to help without having all code in front of me, so I hope I helped you.

**Comment by kerrison24** [comment]
hey @MacKentoch, the view height 500 is just there for debugging, don't mind that.

My navigator is in index.android.js, which gets passed to each component:
```javascript
constructor(props) {
    super(props)
    this.state = {
      email: "",
      password: "",
      component: null
    }
  }

  componentWillMount() {
    AsyncStorage.getItem('user_data').then((user_data_json) => {
      let user_data = JSON.parse(user_data_json)
      if(user_data != null) {
        this.setState({
          component: 'UserHome'
        })
      } else {
        this.setState({
          component: 'Root'
        })
      }
    })
  }

  renderScene(route, navigator) {
    switch(route.component) {
      case 'Root':
        return <Root navigator={navigator}/>
        break

      case 'Signup':
        return <Signup navigator={navigator}/>
        break

      case 'Login':
        return <Login navigator={navigator}/>
        break

      case 'UserHome':
        return <UserHome navigator={navigator}/>
        break
    }
  }

  render() {
    if(this.state.component) {
      return (
        <Navigator
          initialRoute={{component: this.state.component}}
          renderScene={this.renderScene.bind(this)}
          configureScene={(route, routeStack) =>
            Navigator.SceneConfigs.HorizontalSwipeJump}
          />
      )
    } else {
      return (
        <View>
        </View>
      )
    }

  }

```

I attempted to add a configureScene prop to the Navigator, but it made no difference in my case.

The render function I posted previously is in a separate component, the "UserHome" component.

This is my Header component, if that's of any use:
```javascript
constructor(props) {
    super(props)
    this.state = {
      usersInitial: 'K',
      openSideMenu: this.props.initialMenuState
    }
  }

  onMenuToggle() {
    var newState = !this.state.openSideMenu
    this.setState({ openSideMenu: newState })
    this.props.callbackParent(newState)
  }

  render() {
    return (
      <View style={Styles.header}>
        <View style={Styles.headerItem}>
          <Text style={Styles.headerText}>Exma</Text>
        </View>
        <View style={Styles.headerItem}>
          {  !this.props.loaded &&
              <GiftedSpinner />
          }
        </View>
        <View style={Styles.headerItemLetter}>
            <Text style={Styles.headerTextLetter} onPress={this.onMenuToggle.bind(this)}>{this.state.usersInitial}</Text>
        </View>
      </View>
    )
  }
```

**Comment by ArondeParon** [comment]
Would love to hear if you finally managed to solve this problem. I am experiencing the same issue: the drawer starts in an "open" state even though the `isOpen` parameter is `false`.

**Comment by Paul-Todd** [comment]
Your SideMenu component must be the outermost component in your view component/control - if you have it nested inside a view in the control then I saw this behaviour

**Comment by hey-mx** [comment]
Hi,

I have the same issue in my app, I am sure that isOpen start as false but the menu element is showing all the time.

```
import React, {Component} from 'react';
import {Dimensions,ListView,ScrollView,StatusBar,Text,TouchableOpacity,View} from 'react-native';
import Icon from 'react-native-vector-icons/Ionicons';
import {Colors as JoboColors} from '../styles/General';
import SideMenu from 'react-native-side-menu';
//import SideBar from './SideBar';

export default class JobList extends Component {
    state = {
      isOpen: false,
    };

    handleMenu = () => {
        this.setState({isOpen: !this.state.isOpen});
    }

    updateMenuState = (isOpen) => {
        this.setState({ isOpen});
    }

    render() {
        const myMenu = <UserMenu />;
        return (
            <SideMenu menu={myMenu}
                isOpen={this.state.isOpen}
                onChange={this.updateMenuState}>
                <View>
                    <StatusBar
                        backgroundColor= {JoboColors.orangeC}
                        barStyle="light-content"
                        translucent={false}/>
                    <View style={styles.actionBar}>
                        <TouchableOpacity style={styles.menuIcon} onPress={this.handleMenu}>
                            <Icon name="ios-menu" size={32} style={styles.actionBarIcons}/>
                        </TouchableOpacity>
                        <Icon name="ios-search" size={30} style={styles.actionBarIcons}/>
                    </View>
                    <View style={{backgroundColor: 'white', justifyContent: 'center', flex: 1}}>
                        <Text>This is the content</Text>
                    </View>
                </View>
            </SideMenu>
        );
    }
}

class UserMenu extends Component {
    render() {
        return(
            <ScrollView style={styles.content}>

            </ScrollView>
        );
    }
}

const styles = StyleSheet.create({
  actionBar: {
    height: 50,
    flexDirection: 'row',
    backgroundColor: Colors.orangeA,
    alignItems: "center",
    padding: 15,
  },
  actionBarIcons: {
    color: "white",
  },
  menuIcon: {
    flex: 2,
  },
  content: {
    backgroundColor: 'blue',
  },
});```

Somebody could fix this problem?

**Comment by Kureev** [comment]
@hey-mx, by default, all views in RN has no background (transparent). Please, consider adding background to the SideMenu child element.

**Comment by mannok** [comment]
For those who want to help, I am here to explain the phenomenon more detail
![issues](https://cloud.githubusercontent.com/assets/458220/23959282/bb76da4e-09df-11e7-98ef-45d3e108c565.gif)

CAN ANYONE HELP!!!?

**Comment by Kureev** [comment]
@mannok can you please provide the code? Did you try adding background color to the view like it is outlined [here](https://github.com/react-native-community/react-native-side-menu/issues/227#issuecomment-286080914)?

**Comment by mannok** [comment]
@Kureev Sure I did it.

`import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View
} from 'react-native';
import Nav from './components/Nav';

export default class MyApp extends Component {
  render() {
    return (
      <Nav />
    );
  }
}

AppRegistry.registerComponent('MyApp', () => MyApp);`

**Comment by Kureev** [comment]
@mannok I believe you need to set a `backgroundColor` to your `HomeView.js` component.

Example:
```jsx
import React from 'react';
import {
  View,
  TextInput
} from 'react-native';

const styles = {
  container: {
    backgroundColor: '#CCC',
  },
};

export default function HomeView() {
  return (
    <View style={styles.container}>
      <TextInput placeholder='textinput' />
    </View>
  );
}
```

**Comment by loloof64** [comment]
Thanks : having the same problem, and setting a backgroundColor on the main view fixed the problem.

**Comment by thomaslitton** [comment]
I'm having a similar problem:

  <SideMenu
        menu={<Text>just some text</Text>}
        menuPosition="right"
        isOpen={false}
        onChange={(isOpen) => console.log("Side menu change", isOpen)}
  >
       <Text>Main Content</Text>
  </SideMenu>

both "just some text" and "Main Content" are visible on the screen.  

Thanks!

**Comment by jqn** [comment]
@thomaslitton  same as @loloof64 setting the background color in your main container view fixes the problem

**Comment by ASchwad** [comment]
In my case, it was always in front. So just setting the background color didnt fix the issue for me. I added `style={{zIndex: -1}}` to the View in menu to fix the issue.
