### ISSUE TITLE
sometimes can't slide with scrollable-tab-view

### ISSUE THREAD

**Issue by mxyue** [react-native-community/react-native-side-menu#230]
I use with react-native-scrollable-tab-view. A tab component add side menu. when I reload, it work fine, but close side menu，it can't slide open。 
![image](https://cloud.githubusercontent.com/assets/9766601/16354249/d3a9452e-3abf-11e6-8fce-45ac9e6c3e8a.png)  and sometimes the left has blank

`<ScrollableTabView initialPage={0} renderTabBar={() => <BottomTabBar />}
                               tabBarBackgroundColor="#efefef"
                               tabBarPosition='overlayBottom'
            >
                <SideMenu menu={menu }>
                    <TodoApp navigator={this.props.navigator} />
                </SideMenu>
</ScrollableTabView>
`

**Comment by hoangnm** [comment]
I've got this issue too, any idea ?

**Comment by mxyue** [comment]
I replaced it with [react-native-drawer](https://github.com/root-two/react-native-drawer)

**Comment by pareekkhushboo77** [comment]
@mxyue  hie, i am a new bie in react-native , could you help me out about how to start up using drawer and how to use project.

**Comment by mxyue** [comment]
@pareekkhushboo77   I open my react-native program you can read the code [habit_formating](https://github.com/mxyue/habit_formation),  Drawer  in the habit_formation/app/containers/defaultPage.js。
