### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by pareekkhushboo77** [react-native-community/react-native-side-menu#232]
i am a newbie in react-native, dont mind if i ask a basic question, but i wanted to know 
what is the step by step procedure to run this app , 

Any help regarding this will be great.

**Comment by pareekkhushboo77** [comment]
@Kureev I have to implement side drawer navigation , need help..

**Comment by Kureev** [comment]
Hi @pareekkhushboo77!

First of all, I'm sorry for the late response. I recommend you to read an [installation guide](https://github.com/react-native-community/react-native-side-menu#installation) first. Then, you can take a look on our [Basic example](https://github.com/react-native-community/react-native-side-menu/tree/master/examples/Basic) code to get a good overview of "how it works".

**Comment by Kureev** [comment]
Don't hesitate to ask more questions on StackOverflow, it's a way better place (than GH issues) to ask this kind of questions!
