### ISSUE TITLE
#import "RCTRootView.h" error

### ISSUE THREAD

**Issue by pareekkhushboo77** [react-native-community/react-native-side-menu#233]
I downloaded the project and build ,following error generates

/Users/mac/Downloads/react-native-basic/examples/Basic/ios/Basic/AppDelegate.m:12:9: fatal error: 'RCTRootView.h' file not found
#import "RCTRootView.h"
        ^
1 error generated.

** BUILD FAILED **

Please Help, I am a newbie in React Native.

**Comment by pareekkhushboo77** [comment]
@Kureev Please help!

**Comment by Kureev** [comment]
Probably, example is a bit outdated. I'll try to update it asap.

**Comment by Kureev** [comment]
Hi @pareekkhushboo77!

I've updated our example in the repo. It should work flawlessly now ❤️
