### ISSUE TITLE
Transition Callback

### ISSUE THREAD

**Issue by WsCandy** [react-native-community/react-native-side-menu#234]
Hey, 

Would it be possible to implement a transition callback that returns`isOpen` to go a long with the `onChange` prop?

I have an instance in the app I'm creating where the side menus `isOpen` prop is controlled via a state. I need to set the state when the menu opens/closes via the swipe action, using the `onChange` prop causes a stutter in the animation as the state is set (or just closes it again if I don't directly manipulate the `isOpen` state to the correct value).

It would be handy to keep track of the side menus state without having the site effect of a stutter in the animation.

**Comment by Kureev** [comment]
Can it be that `onMove` callback is what you're looking for?

**Comment by WsCandy** [comment]
Thanks for the suggestion, I'll look at implementing it over the coming days and let you know if it's an adequate solution.
