### ISSUE TITLE
Example app crashes

### ISSUE THREAD

**Issue by hfogelberg** [react-native-community/react-native-side-menu#238]
Hi,

I was going to run the example app (iOS) but it red screens on startup with the error message 
'Cannot find entry file index.ios.js in any of the roots: [""../../"]'

Any suggestions?

**Comment by Kureev** [comment]
Hi @hfogelberg!

Thanks for the issue! Indeed, I forgot to remove `--projectRoots` flag from `npm start` script. I've pushed a new version to git, so it should be fixed if you pull!
