### ISSUE TITLE
Open / Close SideMenu with function

### ISSUE THREAD

**Issue by jcathom** [react-native-community/react-native-side-menu#239]
Hello, Thank you for this wonderful Module! I cannot find how to open and close the SideMenu without using movement , calling a function. Is it possible ? For example automatically close the menu when the user touched an item inside the sideMenu ?

Thx a lot :)

**Comment by Kureev** [comment]
Hi @jcathom!

Sure it's possible. In a sake of making a props-driven component, we use `isOpen` prop to determine component state. If you want to change it, just write a function that change this prop. [You can find an example in our `examples` folder. It's a rough implementation, but should be fine to explain the idea](https://github.com/react-native-community/react-native-side-menu/blob/master/examples/Basic/Basic.js)
