### ISSUE TITLE
undefined is not a function (evaluating this.function() in react native

### ISSUE THREAD

**Issue by vikiesakki** [react-native-community/react-native-side-menu#242]
When i am get the data from onPress function its showing the error
```jsx
{this.state.UserValid.map(function(time){
  return (
    <TouchableHighlight onPress={() => this.weeklySheet(time.week_date)}>
      <View style={styles.childView}>
        <View style={styles.listChildView}>
          <Text style={styles.listChildText}>{time.week_date}</Text>
        </View>
        <View style={styles.listChildView}>
          <Text style={styles.listChildText}>{time.hours}</Text>
        </View>
      </View>
    </TouchableHighlight>
  );
}
```

**Comment by Kureev** [comment]
Hi @vikiesakki,

I think you have an issue with the iterator context. Every time you make a `function` it creates a new scope, so `this` in `this.weeklySheet` doesn't refer to the component's scope. I changed your code a little bit:

```js
{this.state.UserValid.map((time) => (
  <TouchableHighlight onPress={() => this.weeklySheet(time.week_date)}>
    <View style={styles.childView}>
      <View style={styles.listChildView}>
        <Text style={styles.listChildText}>{time.week_date}</Text>
      </View>
      <View style={styles.listChildView}>
        <Text style={styles.listChildText}>{time.hours}</Text>
      </View>
    </View>
  </TouchableHighlight>
)}
```

should be working now 😉

**Comment by vikiesakki** [comment]
Thanks man it working. You make me happy Thank you...

**Comment by Vinukrishnan** [comment]
![screenshot_1503560177](https://user-images.githubusercontent.com/30145080/29655100-60071a6c-88cd-11e7-8e17-a7e88a41af4d.png)

**Comment by Vinukrishnan** [comment]
its shows error help me

**Comment by ChenYCL** [comment]
first delete nodu_modules,then npm install , 
comment some error codes
I tried it，and it wroks

**Comment by adnanali-indpro** [comment]
onPress={this.function} and onPress={()=>this.function()} will make difference for the current context

**Comment by ChirantanPatel** [comment]
@Kureev thank's for the suggestion. it working good.


{this.state.UserValid.map((time) => (
  <TouchableHighlight onPress={() => this.weeklySheet(time.week_date)}>
    <View style={styles.childView}>
      <View style={styles.listChildView}>
        <Text style={styles.listChildText}>{time.week_date}</Text>
      </View>
      <View style={styles.listChildView}>
        <Text style={styles.listChildText}>{time.hours}</Text>
      </View>
    </View>
  </TouchableHighlight>
)}
