### ISSUE TITLE
As of Side Menu, transition to the SecondView?

### ISSUE THREAD

**Issue by gHashTag** [react-native-community/react-native-side-menu#246]
As of Side Menu, component react-native-side-menu, to make the transition to the SecondView?

``` jsx
import SecondView from './secondview'
export default class Menu extends Component {
  render () {
    return (
      <ScrollView scrollsToTop={false} style={styles.menu}>
        <Text style={styles.name}>Game</Text>
        <Text
          onPress={() => this.props.onItemSelected('OneView')}
          style={styles.item}>
          Submenu1
        </Text>
        <Text
          onPress={() => this.props.onItemSelected('SecondView')}
          style={styles.item}>
          Submenu2
        </Text>
      </ScrollView>
    )
  }
}
```

**Comment by Kureev** [comment]
Hi @gHashTag, could you be so kind to rephrase the question?

**Comment by gHashTag** [comment]
react-native-router-flux :)

**Comment by Kureev** [comment]
I think you're asking for an example here. I'm currently out of time to make it. Probably, somebody from the community would like to pick it up

**Comment by rochapablo** [comment]
@gHashTag news?

https://github.com/react-native-community/react-native-side-menu/issues/301

**Comment by gHashTag** [comment]
@rochapablo 
Thanks
Now working on this  https://github.com/react-community/react-navigation/
