### ISSUE TITLE
Navigator + Sidemenu doesn't work

### ISSUE THREAD

**Issue by jorgeargds** [react-native-community/react-native-side-menu#249]
Hello @Kureev 
It seems like using the navigator component + the sidemenu doesn't work do you know how to fix this issue or any advice to handle it.
Regards,
Jorge.

**Comment by Kureev** [comment]
Hi @jorgeargds! Could you be so kind to elaborate what do you mean by " it doesn't work"?

**Comment by jorgeargds** [comment]
I'll close the issue, my issue was because the sidemenu doesn't had anything inside of it so was always visible but after I put a view and a text inside it it works perfectly.
Thanks.
