### ISSUE TITLE
I have no clue how to do this!

### ISSUE THREAD

**Issue by jomla97** [react-native-community/react-native-side-menu#256]
I've been trying to understand this for days now, having posted a question on both Reddit and Stackoverflow without any success I'm at a loss. I've created a new project to try to understand it without too many moving parts. This is my index.ios.js:
```

import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View,
  Navigator,
  TextInput,
  AlertIOS,
  Alert,
  Menu,
  ContentView,
} from 'react-native';

import GLOBALS from './app/components/globals.js';
const SideMenu = require('react-native-side-menu');

export default class mbab_internal extends Component{
//class mbab_internal extends Component{
  render(){
    const menu = <Menu navigator={navigator}/>;

    return(
      <Navigator
        initialRoute={{id: 'login'}}
        renderScene={(route, navigator) => {
            if(route.id === "login"){
              return(
                <Text>TEST</Text>
              );
            }
          }
        }
      />
      <SideMenu menu={menu}>
        <ContentView/>
      </SideMenu>
    );
  }
}

AppRegistry.registerComponent('mbab_internal', () => mbab_internal);
```
With this code I get the error "SyntaxError /Users/myusername/mbab_internal/index.ios.js: Adjacent JSX elements must be wrapped in an enclosing tag (35:6)".

I've also tried to remove the Navigator like so:

```
import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View,
  Navigator,
  TextInput,
  AlertIOS,
  Alert,
  Menu,
  ContentView,
} from 'react-native';

import GLOBALS from './app/components/globals.js';
const SideMenu = require('react-native-side-menu');

export default class mbab_internal extends Component{
//class mbab_internal extends Component{
  render(){
    const menu = <Menu navigator={navigator}/>;

    return(
      <SideMenu menu={menu}>
        <ContentView/>
      </SideMenu>
    );
  }
}

AppRegistry.registerComponent('mbab_internal', () => mbab_internal);

```

But in this case I instead get the error "Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. Check the render method of 'mbab_internal'".

Any help is highly appreciated! I'm very new to React Native and I'm eager to learn!

**Comment by abbasfreestyle** [comment]
You have several problems.

Importing Menu and ContentView from 'react-native' is wrong because they don't exist there.
These are meant to be your own custom components.
<Menu /> is what you display in your menu.
ContentView is your content inside the side menu. i.e. <Navigator />

You need to do something like this:

```
import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View,
  Navigator,
  TextInput,
  Alert,
} from 'react-native';

import Menu from './app/components/mycustommenu.js';
import GLOBALS from './app/components/globals.js';
const SideMenu = require('react-native-side-menu');

export default class mbab_internal extends Component{

  render(){
    return(
      <SideMenu menu={<Menu navigator={navigator}/>}>
         <Navigator initialRoute={{id: 'login'}}
            renderScene={(route, navigator) => {
            if(route.id === "login"){ return(<Text>TEST</Text>); }
          }} />
      </SideMenu>
    );
  }

}

AppRegistry.registerComponent('mbab_internal', () => mbab_internal);
```

**Comment by jomla97** [comment]
@abbasfreestyle Thank you! This solved it finally.. I appreciate the help, I'm very new to React Native and I've boiled my brain trying to wrap my head around it the last week or two.

**Comment by jomla97** [comment]
@abbasfreestyle Actually. I got the SideMenu working and got my content where it's supposed to be but I forgot about the "menu={<Menu navigator={navigator}/>}". With this I still get the same error ("Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. Check the render method of 'mbab_internal'").

Would you mind explaining what "menu={<Menu navigator={navigator}/>}" means and how to fix it?

**Comment by abbasfreestyle** [comment]
It's returning undefined because it doesnt know what class to look for in that file. You can do the following

module.exports = Menu;
At the end of the file
Or just
export default class Menu extends Component
Instead of
class Menu extends Component
(if my memory is correct)

**Comment by jomla97** [comment]
@abbasfreestyle `export default` works like a charm! Thank you so much!

**Comment by abbasfreestyle** [comment]
You're welcome :)
