### ISSUE TITLE
Alternating between menuPosition 'left' and 'right'

### ISSUE THREAD

**Issue by antoniuschan99** [react-native-community/react-native-side-menu#262]
I am having trouble getting sidemenu to open from left and right side properly. I have two hamburgers one on top left and other top right. When i click on one, it sets the state to 'left' or 'right' - this.props.parentRef.setState({sideMenuPosition: 'right'}) -
 In < SideMenu > I have menuPosition={this.state.sideMenuPosition} 

However, this does not work: menuPosition={this.state.sideMenuPosition} 
doesn't get the correct value. I have to press the hamburger a second time before the correct value is received and the correct side menu position is opened.

Any reason why this is the case? I'm a newb to react native. Is it possible to set the props of a component (in this case SideMenu) from another component?

**Comment by Kureev** [comment]
If you have two different menus, why not to use two different React Elements for it?
Instead of having a menu position as a state, you may just use another `<SideMenu />`.

**Comment by kevin611003** [comment]
@antoniuschan99  i have the same trouble,did you solve this trouble?

**Comment by HoangTrung** [comment]
I run into the same problem. @Kureev how to use 2 sidemenu contain same screen ?

**Comment by HoangTrung** [comment]
Solved. 
Just put another sidebar menu inside. So we have 1 sidebar position left, contain 1 sidebar position right content screen content.

**Comment by Kureev** [comment]
Yes, or you can use `zIndex` to push it "below" the other one

**Comment by antoniuschan99** [comment]
thank you, I will try this out. 

@kevin611003 Did it work for you? I just used another view

**Comment by kevin611003** [comment]
it's ok now.
```
<SideMenu
    menu={menu}
    isOpen={this.state.isLeftOpen}
    menuPosition='left'>

   <SideMenu
        menu={menu}
        isOpen={this.state.isRightOpen}
        menuPosition='right'>

            //content

   </SideMenu>
</SideMenu>
```

**Comment by chung2014** [comment]
@Kureev  you mentioned we can use `zIndex` to push the sidebar menu below. I don't quite understand how it works? Can you use @kevin611003 sample above to explain a bit more on it. e.g if I want the left sidebar menu at the most top, how should I set it?

**Comment by Kureev** [comment]
You know, I just realized that the solution @kevin611003 proposed is the best one. `zIndex` won't work really. Sorry for the misleading info.

**Comment by acollazomayer** [comment]
This is not working in production. I dont know why but the right menu is rendering right next to the left
