### ISSUE TITLE
Menu is always visible even when isOpen is false

### ISSUE THREAD

**Issue by davidcaseria** [react-native-community/react-native-side-menu#267]
Video:
![device-2017-03-02-213512](https://cloud.githubusercontent.com/assets/5961402/23537321/ca1c5d0c-ff90-11e6-8642-6a499ce674cc.gif)

Code:
```
class Menu extends Component {

  render() {
    return (
      <View style={{flex: 1, backgroundColor: '#ededed', paddingTop: 50}}>
        <List containerStyle={{marginBottom: 20}}>
          { this.props.routes.map((r, i) => (<ListItem key={i} title={r.title} onPress={() => console.log('Pressed ' + r.title)} /> )) }
        </List>
      </View>
    );
  }
}

export default class Main extends Component {

  constructor(props) {
    super(props);
    this.state = {isOpen: false};
    this.toggleSideMenu = this.toggleSideMenu.bind(this)
  }

  toggleSideMenu () {
    this.setState({isOpen: !this.state.isOpen})
  }

  updateSideMenuState(isOpen) {
    this.setState({ isOpen, });
  }

  render() {
    const routes = [
      {title: 'First Scene', text: 'Hi!', index: 0},
      {title: 'Second Scene', text: 'Hello!', index: 1},
    ];

    const menu = (<Menu navigator={this.props.navigator} routes={routes} />);

    return (
        <SideMenu isOpen={this.state.isOpen} onChange={(isOpen) => this.updateSideMenuState(isOpen)} menu={menu}>
          <View style={{paddingTop: 50}}>
            <Text>Hi!</Text>
          </View>
        </SideMenu>
    );
  }
}
```

**Comment by Kureev** [comment]
Can you also post a `Menu` code? That will help to exclude a possibility of usage mistake

**Comment by davidcaseria** [comment]
@Kureev thanks helping! I believe the code you're talking about is posted above:
```
class Menu extends Component {

  render() {
    return (
      <View style={{flex: 1, backgroundColor: '#ededed', paddingTop: 50}}>
        <List containerStyle={{marginBottom: 20}}>
          { this.props.routes.map((r, i) => (<ListItem key={i} title={r.title} onPress={() => console.log('Pressed ' + r.title)} /> )) }
        </List>
      </View>
    );
  }
}
```

I'm using the `List` component from [react-native-elements](https://github.com/react-native-community/react-native-elements#lists).

Let me know if you're looking for something else.

**Comment by alusor** [comment]
Yep, i have the same error but only on android, on ios works perfectly, so at the moment i unable to resolve the problem
![screenshot_20170306-003352](https://cloud.githubusercontent.com/assets/9580544/23599141/c47b0918-0204-11e7-8db8-bf4f89c29007.png)
![screenshot_20170306-003400](https://cloud.githubusercontent.com/assets/9580544/23599142/c47d2cc0-0204-11e7-9818-fe568ce94890.png)

**Comment by railsfactory-sivamanikandan** [comment]
@Kureev @alusor @davidcaseria Did you fix this? I too got the same issue

**Comment by railsfactory-sivamanikandan** [comment]
@Kureev  @alusor  @davidcaseria  if backgroundColor is set for the container this issue will not occur. After setting back ground color it is working fine in IOS

**Comment by davidcaseria** [comment]
@railsfactory-sivamanikandan Yes, setting the `backgroundColor` and `flex` fixes the issue.
