### ISSUE TITLE
Menu not defined

### ISSUE THREAD

**Issue by bspatil0001** [react-native-community/react-native-side-menu#271]
Hi,

It is giving error as Menu not defined.

**Comment by mireen** [comment]
I have the same error !

**Comment by mattmacadams** [comment]
same..

**Comment by Kureev** [comment]
I believe you experience this issue because you're trying to `import` SideMenu, but the menu uses `modules.export` instead of `export default`. This needs to be changed, but so far the way to fix your issue is to use `require`. I'll try to fix it asap

**Comment by jmcartlamy** [comment]
You must create yourself a component named `Menu` that you import in your component using `SideMenu`. For example :

**App.js**
```
import React, { Component } from 'react';
import Menu from '../components/Menu.js';

class App extends Component {

   render() {
      return (
         <SideMenu menu={<Menu {...this.props}/>}>
           <View>
               <Text>Main page</Text>
           </View>
         </SideMenu>
     );
   }
}
export default App;
```

**Menu.js**
```
import React, { Component } from 'react';

class Menu extends Component {

   render() {
     return (
        <ScrollMenu scrollsToTop={false}>
           <View>
              <Text>
                 Item 1
              </Text>
              <Text>
                 Item 2
              </Text>
           </View>
        </ScrollMenu>
     );
   }
}

export default Menu;
```

**Comment by Kureev** [comment]
temporary workaround:
```js
import SideMenu from 'react-native-side-menu';
```
replace by
```js
import SM from 'react-native-side-menu';
const SideMenu = SM.default;
```

**Comment by z3t0** [comment]
None of the work around suggested seem to work... using @jmcartlamy solution errors with ScrollMenu not defined

using @Kureev solution doesnt seem to change anything. Thoughts?

**Comment by jmcartlamy** [comment]
@z3t0 Sorry, replace ScrollMenu by `ScrollView`, and import it with react-native

**Comment by Kureev** [comment]
From now on (v1.0.0) this library support `import SideMenu from 'react-native-side-menu` syntax 🎉 . I think this issue can be closed now.

**Comment by praveen70** [comment]
i have a sidebar with links menus when i point my cursor it should show the submenu list which i coded but the thing is react-bootstrap, react don't support  i am getting menu not define error is there any other way to resolve my error

**Comment by praveen70** [comment]
class ToggleMenu extends React.Component {
    constructor(props) {
        super(props);

        this.state = {
            visible: false  
        };

        this.toggleMenu = this.toggleMenu.bind(this);
    }

    toggleMenu() {
        this.setState({visible: !this.state.visible})
    }

    render() {
        return (
            <div>
                <button onClick={this.toggleMenu}>Show Right Menu!</button>
                {this.state.visible && <Menu alignment="right">
                <MenuItem hash="first-page">First Page</MenuItem>
                <MenuItem hash="second-page">Second Page</MenuItem>
                <MenuItem hash="third-page">Third Page</MenuItem>
                </Menu>}
            </div>
        );
    }
}

this is my codes

**Comment by elhardoum** [comment]
Combining both solutions has worked for me:

```javascript
// src/component/Menu.js
import React, { Component } from 'react';
import { ScrollView, Text, View } from 'react-native';

export default class Menu extends Component {
   render() {
     return (
        <ScrollView scrollsToTop={false}>
           <View>
              <Text>
                 Item 1
              </Text>
              <Text>
                 Item 2
              </Text>
           </View>
        </ScrollView>
     );
   }
}
```

```javascript
// index.js (or App.js)
import React, { Component } from 'react';
import { AppRegistry } from 'react-native';
import Render from './src/component/Render.js'
import Menu from './src/component/Menu.js'

const SideMenu = require('react-native-side-menu').default;

export default class App extends Component {
  render() {
    return (
      <SideMenu menu={<Menu/>}>
        <Render/>
      </SideMenu>
    );
  }
}

AppRegistry.registerComponent('someapp', ()  => App);
```

Thanks.
