### ISSUE TITLE
No shadow for navbar with react navigation

### ISSUE THREAD

**Issue by RWOverdijk** [react-native-community/react-native-side-menu#277]
When using react-navigation with this component, the navbar doesn't have a shadow:

<img width="459" alt="screenshot 2017-04-25 20 32 21" src="https://cloud.githubusercontent.com/assets/781745/25401560/4e588d5e-29f6-11e7-8206-f86a4a56e978.png">

**Comment by Kureev** [comment]
Hi @RWOverdijk!

Sorry for the late response. I think it depends by the composition model you use. Can you provide some code, please?
