### ISSUE TITLE
Side Menu Overlay Transition

### ISSUE THREAD

**Issue by mohit-pandey** [react-native-community/react-native-side-menu#278]
Hi,

Is there any way with which we can open the side menu with overlay transition, instead of sliding main scene to right, something like nativebase does:
https://github.com/GeekyAnts/NativeBase-KitchenSink/blob/master/screenshots/iOS.gif

**Comment by petrgazarov** [comment]
You can use [react-native-drawer](https://github.com/root-two/react-native-drawer) to achieve this, hope this might save time for those looking for it!

**Comment by Kureev** [comment]
Agree, I recommend to use `react-native-drawer` for this kind of experience

**Comment by l-Marty-l** [comment]
Sorry, but `react-native-drawer` is slow and not recommend to use. `react-native-navigation` has a better drawer, but requires the annoying navigation container and `react-native-side-drawer` seem to have overlay issues at me, although seem to be the most applicable alternative available.
