### ISSUE TITLE
this.props.navigation is undefined

### ISSUE THREAD

**Issue by viane** [react-native-community/react-native-side-menu#279]
How can I pass props.navigation from sidebar to menu?
Right now im using 
`const menu = <Menu onItemSelected={this.onMenuItemSelected} navigator={this.props.navigator}/>;`
isn't working, when I try to push/replace the navigation in menu.js it got undefined.

 //app.js

             <SideMenu
                menu={menu}
                isOpen={this.state.isMenuSideBarOpen}
                onChange={(isOpen)=>{this.updateMenuState(isOpen)}}
              >
                <StatusBar
                  backgroundColor="blue"
                  barStyle="light-content"
                />
                <NavigatorIOS
                  initialRoute={{
                    component: HomeScene,
                    title: this.state.selectedItem,
                    leftButtonIcon: this.state.menuIcon,
                    onLeftButtonPress: ()=>{
                      this.toggle();
                    }
                  }}
                  style={{flex: 1}}
                  tintColor="#FFFFFF"
                  titleTextColor="#FFFFFF"
                  barTintColor='#000099'
                >
                </NavigatorIOS>
              </SideMenu>

// menu.js

```
export default class Menu extends Component{
  constructor(props){
    super(props);
  }

  static propTypes={
    onItemSelected: React.PropTypes.func.isRequired,
  };

  _renderRow = (title: string, onPress: Function) => {
    return (
      <View>
        <TouchableHighlight onPress={onPress}>
          <View style={styles.row}>
            <Text style={styles.rowText}>
              {title}
            </Text>
          </View>
        </TouchableHighlight>
      </View>
    );
  };

  render(){
    return(
      <ScrollView scrollsToTop={false} style={styles.sideMenuBar}>
        {this._renderRow("Home", function(){
          this.props.navigator.replace({
            title: 'Home',
            component: HomeScene,
            passProps: {depth: this.props.depth ? this.props.depth + 1 : 1},
            onLeftButtonPress: () => this.props.navigator.pop(),
          });
        })}

        {this._renderRow("Page", function(){
          this.props.navigator.replace({
            title: 'Page',
            component: Page,
            passProps: {depth: this.props.depth ? this.props.depth + 1 : 1},
            onLeftButtonPress: () => this.props.navigator.pop(),
          });
        })}
      </ScrollView>
    )
  }


}

```

**Comment by SelaOren** [comment]
Did you manage to work this out?

**Comment by MichaelPintos** [comment]
<SideMenu menu={<Text>My menu options</Text>}>
        <View>
           <Text> APP CONTENT </Text>
        </View>
  </SideMenu>
//Use this simple example

**Comment by Kureev** [comment]
Hi @viane!

Can you elaborate how you get `navigator` as a prop in `app.js` component having `NavigatorIOS` nested in it? Props are passed from parents to children, not the other way around. I think this is your issue.

Although, I have to say that StackOverflow is a better place for this kind of questions (as far as it isn't a bug in this library).
