### ISSUE TITLE
Unable to resolve module react-native-navbar

### ISSUE THREAD

**Issue by githubmss** [react-native-community/react-native-side-menu#281]
I am just trying to integrate side menu in my demo , but getting issue .

Full description is here on this link :-  https://stackoverflow.com/questions/44275760/unable-to-resolve-module-react-native-navbar/44276207#44276207

Please let me know the exact issue , so that i can make use of your demo .

Thanks

**Comment by githubmss** [comment]
The above error got solved by updating npm version to latest one using command :- npm install npm@latest -g

After that i just do the followings steps :-

1. react-native init sidemenudemo 
2. cd sidemenudemo 
3. npm install react-native-side-menu 
4. place Menu.js file under src/components 
5. Replace code in index.android.js file as mentioned inside demo. 
6. react-native run-android

Now i am getting error :- 

Unable to resolve module react-native-navbar

Details of my versions :-

npm version :- 5.0.1
node version :- 6.1.1
react-native-cli :- 2.0.1
react-native : - 0.44.0

Please let me know what is causing problem

**Comment by Kureev** [comment]
Hi @githubmss!

Sorry for the late response.

I think you just missed one step where you install `react-native-navbar`:
```
$ npm install react-native-navbar --save
```
