### ISSUE TITLE
Using with tabs

### ISSUE THREAD

**Issue by hyochan35** [react-native-community/react-native-side-menu#284]
When using this sidemenu with tabs, in first tab, it looks ok but when I go to second tab There is sidemenu view as a background image doing nothing. When I implemented scrollview in second tab, it shows sidemenu as a background when I scroll down. This is reall annoying.

Below I posted screen shot to let you know for sure.

SCREEN1 : NORMAL IN TAB2
<img width="367" alt="2017-06-09 10 38 37" src="https://user-images.githubusercontent.com/20625109/26957423-f36347c2-4cff-11e7-8e43-6bbb652cd429.png">

SCREEN2: WHEN I DRAG DOWN, DRAWER MENU BACKGROUND STACK SHOWS
![2017-06-09 10 38 59](https://user-images.githubusercontent.com/20625109/26957435-033c57b0-4d00-11e7-871b-2628fda60840.png)

**Comment by carlesnunez** [comment]
Im not really sure but I think that you have a problem fixed by this PR

https://github.com/react-native-community/react-native-side-menu/pull/287

**Comment by carlesnunez** [comment]
@hyochan35 does that fixed your problem? Should me nice if you provide feedback
