### ISSUE TITLE
** BUILD FAILED ** react-native-side-menu-master 2/examples/Basic/node_modules/promise/lib/done.js:10       throw err;       ^

### ISSUE THREAD

**Issue by jpca999** [react-native-community/react-native-side-menu#285]
i downloaded the whole repo, went into the basic folder, then did npm install  and then from teh Basic folder I did react-native run ios  but it gives me following error. 

![image](https://user-images.githubusercontent.com/1026325/27166557-a2e9350e-5169-11e7-8f6e-459ab1c023ab.png)

**Comment by Kureev** [comment]
This is fixed in 1.0.0
