### ISSUE TITLE
Is Swiping SideMenu provided in this library?

### ISSUE THREAD

**Issue by BigPun86** [react-native-community/react-native-side-menu#288]
How can i actually swipe the menu to open and/or close it? Coudn´t figure it out if this actually is possible or not.

**Comment by Kureev** [comment]
Hi @BigPun86!

Currently we have an animation illustrating the main principle of the library (which is a swiping functionality btw). Do you think there is something which is not clear to everyone? 

We would like to improve documentation to make it easy for newcomers, can you advice us something?
