### ISSUE TITLE
Can't find variable App

### ISSUE THREAD

**Issue by hygull** [react-native-community/react-native-side-menu#291]
I tried to replace the App with my app name 'CabBookingApp', but still the error 
```
Can't find variable CabBookingApp
```
is coming

**Comment by jadlmir** [comment]
same problem here

**Comment by Kureev** [comment]
Can you share some code and steps to reproduce the problem, please?

**Comment by Kureev** [comment]
Closed due to lack of feedback. I'll re-open this one if we have a new info from the TS

**Comment by brije111** [comment]
facing the same problem "Can't find variable: App"
![device-2017-09-14-125648](https://user-images.githubusercontent.com/11292348/30417111-3e89861a-994c-11e7-9bc5-b1cdaaf3ab0f.png)

I tried the same code stated here https://react-native-training.github.io/react-native-elements/API/side_menu/
