### ISSUE TITLE
Animation bounce

### ISSUE THREAD

**Issue by Elijen** [react-native-community/react-native-side-menu#292]
When using isOpen prop to open/close the side-menu the animation bounces a little (around 2px) right/left even if `bounceBackOnOverdraw` is set to `false`.

Is there a way to disable this? Furthermore It seems impossible to set background color/view of the overdraw area (it's always white).

![20170705_151938](https://user-images.githubusercontent.com/1304054/27866226-d154363c-6195-11e7-93b6-cb747fbd2b31.GIF)

**Comment by Kureev** [comment]
Hi @Elijen!

Sure, you can overwrite `animationFunction` function. The current implementation can be found here: https://github.com/react-native-community/react-native-side-menu/blob/master/index.js#L293.

**Comment by dengue8830** [comment]
i'm facing the same problem, i can drag the menu to the other side and the content will be stretched until i stop dragging and it returns to its final position. Is there a way to prevent dragging the menu all screen along?

**Comment by andrei-m-code** [comment]
For those who still struggles:
```
<SideMenu
    ...
    animationFunction={(prop, value) => Animated.spring(prop, {
        toValue: value,
        friction: 20,
    })}>...
```
Setting the friction higher prevents it from bouncing in and out of these 2-3 annoying pixels.

P.S. Great library, thanks for sharing!

**Comment by jaelarmasm** [comment]
@andrei-m-code thanks bro!
