### ISSUE TITLE
State (open/close) change callback

### ISSUE THREAD

**Issue by jefby** [react-native-community/react-native-side-menu#295]
Hi, I'm a new in react-native. Trying to use react-native-side-menu and I want to call my callback function when animation is completed. 

Can you help me on this ?

Thanks very much.

**Comment by Kureev** [comment]
HI @jefby!

We have [a section in README](https://github.com/react-native-community/react-native-side-menu#component-props) that documents component interface (i.e. all possible props it can take). 

Based on the issue description, I assume you're looking for a `onChange` handler.

**Comment by jefby** [comment]
@Kureev Hi, `onChange` handler is called when animation begin, but i want to do something when animation is completed, this function is unmet.

**Comment by Kureev** [comment]
I'm pretty sure it is called once animation is complete. Can you try it out, please?

**Comment by jefby** [comment]
Yeah, I am trying now.

**Comment by Kureev** [comment]
Indeed, you're right. I'll try to come up with an API like `onMenuOpened` and `onMenuClosed`

**Comment by macaetano** [comment]
There's any news on this issue?

**Comment by adeteejay** [comment]
@jefby were you able to solve this?
