### ISSUE TITLE
Undefined is not an object (evaluating 'React.PropTypes.Number')

### ISSUE THREAD

**Issue by ShailajaV** [react-native-community/react-native-side-menu#296]
After installing react-native-side-menu when i tried to start the app getting the following error.
Undefined is not an object (evaluating 'React.PropTypes.Number')
localpath://node_modules/react-native-side-menu/index.js(243:32)

Below is my package.json
"react": "^16.0.0-alpha.12",
"react-native": "^0.46.1",
"react-native-side-menu": "^0.20.3",

**Comment by Kureev** [comment]
It happens because current codebase relies on PropTypes in the `react` package. From version 16.x React team moved it to the standalone package. I'll take care of the fix

**Comment by ShailajaV** [comment]
Thank you.

**Comment by Kureev** [comment]
Hi again, @ShailajaV!

Can you try a new version (`1.0.0`), please?

**Comment by ShailajaV** [comment]
i have installed react-side-menu@1.0.0.

In package.json 
"react-native-side-menu": "^1.0.0",

But when running the app it is throwing the following error.

error: bundling failed: "TransformError: localpath\\node_m
odules\\react-native-side-menu\\index.js: Couldn't find preset \"flow\" relative
 to directory \"localpath\\\\node_modules\\\\react-n
ative-side-menu\""

**Comment by Kureev** [comment]
Looks like I've made a mistake. Flow preset issue will be tracked here https://github.com/react-native-community/react-native-side-menu/issues/298

**Comment by ShailajaV** [comment]
Its working fine now. I have installed 1.0.2. Thank you.

**Comment by Kureev** [comment]
Thanks for you feedback, @ShailajaV!
