### ISSUE TITLE
Can't find variable: Menu

### ISSUE THREAD

**Issue by bbucca3** [react-native-community/react-native-side-menu#299]
`import React from 'react';`
`import { Text, View, Button, FlatList, TouchableOpacity } from 'react-native';`
`import { StackNavigator } from 'react-navigation';`
`import PostPreview from './src/PostPreview.js';`

`const SideMenu = require('react-native-side-menu');`

```
export default class HomeScreen extends React.Component {
  static navigationOptions = {
    title: 'Home',
  };

  render() {
    const { navigate } = this.props.navigation;
    const menu = <Menu navigator={navigator}/>;
    return (
      <View>
      <SideMenu menu={menu}>
        <PostPreview/>
      </SideMenu>
        <Text>Hello, Navigation App!</Text>
        <Button
          onPress={() => navigate('SignIn')}
          title="Sign In"
        />
        <Button
          onPress={() => navigate('CreatePosts')}
          title="Create Post"
        />
        <Button
          onPress={() => navigate('Settings')}
          title="View Settings"
        />
        <Text>PostList!!!</Text>
        <FlatList
          data={[{key: 'a'}, {key: 'b'}, {key: 'c'}]}
          renderItem={({item}) => (
            <TouchableOpacity>
              <PostPreview />
              <Button
              title="View Post"
              color="#841584"
              onPress={() => navigate('PostView')} />
            </TouchableOpacity>
            )
          }
        />
      </View>
    );
  }
}

```

**Comment by TimothyMcWatters** [comment]
I am having the same problem and wondering how you fixed your issue. Any help would be greatly appreciated. 

Thanks,
Tim McWatters

**Comment by Kureev** [comment]
With the latest version of SideMenu, you should use `import` instead:
```js
import SideMenu from 'react-native-side-menu';
```

**Comment by fretman92** [comment]
Add **Menu** to the imports of 'react-native'

`import { Text, View, Button, FlatList, Menu, TouchableOpacity } from 'react-native';`

**Comment by Kureev** [comment]
There is no such a thing as `Menu` in `react-native` iirc

**Comment by bingpple** [comment]
Hi @Kureev, I guess you may change your sample code to 
`const menu = <SideMenu navigator={navigator}/>;`, not the one below:
`const menu = <Menu navigator={navigator}/>;`
