### ISSUE TITLE
How to increase performance when combined with ListView

### ISSUE THREAD

**Issue by sitompul** [react-native-community/react-native-side-menu#301]
Hi im using react-native-router-flux and ListView. My code is something like this

```
render() {
	return (
		<SideMenu
			menu={<Sidebar />}
			isOpen={this.props.drawerOpen}
			onChange={this.handleOnChange.bind(this)}
		>
			<ReduxRouter scenes={scenes} />
		</SideMenu>
	);
}
```
inside my ReduxRouter i have scenes like this.
```
const scenes = (
	<Scene key='root'>
		<Scene key='main' component={MainComponent} hideNavBar />
	</Scene>
)
```
inside my MainComponent i have one ListView with 10 rows at initial and additional 5 rows after reach the bottom part.
But after loaded 20++ rows my app appeared to have jitter when i was trying to open my side menu.

What should i do to increase the performance?

Thanks

**Comment by Kureev** [comment]
It could because of various reasons. For instance, you may perform some complex computations at the moment side menu is opening or smth like that. It's very hard for me to debug performance remotely, so I'd recommend to start with a built-in profiler, mb start debugging in Chrome just to check which functions takes most of JS thread time. 

P.S. I never worked with `react-native-router-flux` and therefore can't really tell much about its performance or compatibility with side menu. Although, if you find a bug in side menu component that makes it slow (for some reason), I'll be happy to help fixing it.

P.P.S. Probably, StackOverflow would be a better place to ask this kind of questions.

Best of luck!

**Comment by rochapablo** [comment]
@sitompul any news about this?

**Comment by sitompul** [comment]
@rochapablo im changing my routing method and my drawer approach using this 
https://reactnavigation.org/docs/navigators/stack
https://reactnavigation.org/docs/navigators/drawer

**Comment by rochapablo** [comment]
@sitompul Thank you, maybe I change.

I figure out a way to use react-native-router-flux:

```
class App extends Component {
  constructor() {
    super()
    this.state = {
      isOpen: false
    }
    this.toggleSideMenu = this.toggleSideMenu.bind(this)
    this.closeSideMenu = this.closeSideMenu.bind(this)
  }

  onSideMenuChange(isOpen) {
    this.setState({
      isOpen: isOpen
    })
  }

  toggleSideMenu() {
    this.setState({
      isOpen: !this.state.isOpen
    })
  }

  closeSideMenu() {
    this.setState({
      isOpen: false
    })
  }

  render() {
    const menu = <Menu navigator={navigator} toggleSideMenu={this.toggleSideMenu} />;
    return (
      <SideMenu menu={menu} disableGestures={true} isOpen={this.state.isOpen}>    
        <Router>
          <Scene key="main" hideNavBar={true}>
            <Scene key="login" component={Login} title="Login" onEnter={this.closeSideMenu} />
            <Scene key="chat" component={Chat} title="Chat" toggleSideMenu={this.toggleSideMenu} />
          </Scene>        
        </Router>
      </SideMenu>
    );
  }
}
```

It's working, still I'm not sure if I'm doing in the right way.

Again, thank you.

**Comment by sitompul** [comment]
@rochapablo be careful if you will use a long row ListView inside your Scene component. Because it will slow your performance.

**Comment by Tom29** [comment]
@sitompul hi, did you find any way to solve the trouble?
i've tried with both FlatList and Listview, both brings out bad performance with side menu.
Any better side menu to work with Flatlist?

**Comment by sitompul** [comment]
@Tom29 what kind of routing library do you use?

I managed my situation by changing my code to use sidemenu provided by [reactnavigation](https://reactnavigation.org/)
