### ISSUE TITLE
Animate menu component over current screen rather than animate current screen

### ISSUE THREAD

**Issue by danderson00** [react-native-community/react-native-side-menu#307]
It seems more natural to drag the menu component on to the screen rather than to drag the currently displayed component off the screen.

**Comment by Kureev** [comment]
Hi @danderson00! 
There are different techniques describing how menu can be animated and this is just one of them. You can always go for https://github.com/react-native-community/react-native-drawer-layout or https://github.com/root-two/react-native-drawer to achieve an experience you want to have
