### ISSUE TITLE
onSliding not working

### ISSUE THREAD

**Issue by stephenheron** [react-native-community/react-native-side-menu#316]
Hi,

I am trying to get the onSliding prop working but it does not seem to get called.

It looks as if it has not been added to the build/index.js file. If I run 'npm run-script build' it is called as expected.

I am new to the npm ecosystem so not quite sure what the exact fix is.

Thanks,
Stephen

**Comment by Kureev** [comment]
Hi @stephenheron!

Which version of `reat-native-side-menu` do you use? I believe `onSliding` has been introduced in `1.1.0` and not supported in prior versions.

**Comment by stephenheron** [comment]
Hi @Kureev 

In my package.json I have "react-native-side-menu": "^1.1.0".

I will try deleting the node_modules directory and reinstalling just to see if that fixes it.

Thanks,
Stephen

**Comment by Kureev** [comment]
Probably you can also provide a code example so I can take a look? It is hard to debug an issue without any context 😞

**Comment by stephenheron** [comment]
Hi @Kureev 

Deleted node_modules and reinstalled but no luck.

Here is my code:

`<ReactNativeSideMenu
                menuPosition="right"
                isOpen={this.props.menuStore.isOpen}
                onSliding={(status) => console.log(status)}
                onChange={(isOpen) => this.props.menuStore.setOpen(isOpen)}
                openMenuOffset={Math.round(Dimensions.get('window').width * 0.75)}
                bounceBackOnOverdraw={false}
                disableGestures={true}
                menu={menu}
                >
                {this.props.children}
</ReactNativeSideMenu>`

I don't get any console.log entries when sliding however I run the commands below then it does work after reloading.

`cd node_modules/react-native-side-menu/
npm run-script build` 

Thanks,
Stephen

**Comment by Kureev** [comment]
You don't have to run these commands by yourself. Although, it shouldn't do any harm as well. I'll take a look on your code and try to come up with a solution from you 👍

**Comment by Kureev** [comment]
I confirm it is a bug. I'm on it.

**Comment by Kureev** [comment]
`1.1.3` should fix it. Can you please give it a try?

**Comment by stephenheron** [comment]
Hi @Kureev 

Nice one! 

That seems to be working now when I upgraded to 1.1.3

Thanks for the help. I will let you do the honours of closing the issue. ;-)

Thanks,
Stephen

**Comment by Kureev** [comment]
Haha thanks for reporting this, @stephenheron!
