### ISSUE TITLE
Undefined is not an object (evaluating '_react2.PropTypes.number')

### ISSUE THREAD

**Issue by Vishwanath1688** [react-native-community/react-native-side-menu#320]
After installing react-native-md-textinput when i tried to start the app getting the following error.
Undefined is not an object (evaluating 'React.PropTypes.Number')
underline.js

Below is my package.json

    "react": "16.0.0",
    "react-native": "^0.49.5",
    "react-native-md-textinput": "^2.0.4",
    "react-navigation": "^1.0.0-beta.19"

**Comment by Vishwanath1688** [comment]
Solved it by importing PropTypes from 'prop-types' instead of 'react-native'

import React, {Component } from "react";
import PropTypes from 'prop-types';

**Comment by santosh4307** [comment]
imported in my js file 

import React, { Component } from 'react'
import { View, Text, TouchableOpacity, TextInput, StyleSheet ,Image, TouchableHighlight,} from 'react-native'
import { StackNavigator } from 'react-navigation';
import TextField from 'react-native-md-textinput';
import PropTypes from 'prop-types';


and this is my index.js file
import { AppRegistry } from 'react-native';
import App from './App';


module.exports.PropTypes = require('prop-types');
let createClass;
Object.defineProperty(module.exports, 'createClass', {
  get: function() {
    if (!createClass) {
      createClass = require('create-react-class').bind(module.exports);
    }
    return createClass;
  }
});


AppRegistry.registerComponent('hellodemo', () => App);

still getting same error ..

**Comment by MITDD6338** [comment]
Hi there, I got this error : undefined is not an object (evaluating ‘_react2.PropTypes.number’)


How can I fix it ? I’m using react-native@0.53.0
