### ISSUE TITLE
Is there a way to make side menu appear on top of app Content?

### ISSUE THREAD

**Issue by tonyneel923** [react-native-community/react-native-side-menu#332]
By default the app content lays on top and is what is moved away. Is it possible to have the side menu be what is animated and have it lay on top?

![image](https://user-images.githubusercontent.com/5866014/37055718-68227ea0-2150-11e8-81f0-66326b877015.png)

Like this image.

Thanks for any help!

**Comment by davidthornton** [comment]
Yes there is - it's the default for the `DrawerNavigator` in react-navigation: https://reactnavigation.org/docs/drawer-based-navigation.html.

**Comment by RuthenicEye** [comment]
Looking for something like this myself. If anyone knows any method please do share

**Comment by nes123** [comment]
+1

**Comment by gabitoesmiapodo** [comment]
Any news on how to do this?

**Comment by nes123** [comment]
I just defined the “main app” as the menu and start everything with open “menu” and it works great

**Comment by chakrihacker** [comment]
Please use react navigation drawer component for this use case
