### ISSUE TITLE
componentWillMount has been renamed, and is not recommended for use

### ISSUE THREAD

**Issue by kking937** [react-native-community/react-native-side-menu#393]
# Bug

In index.js, SideMenu is using componentWillMount to set this.responder. In the current React version, documentation states that UNSAFE_componentWillMount should be used and that componentWillMount will work until version 17.

## Steps To Reproduce

Use this code on the most recent version of React native

Describe what you expected to happen:

Not get a warning

**Comment by chakrihacker** [comment]
There is a PR #384
